services:
  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=croix-rouge-test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

