name: CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_HEADER: ${{ secrets.JWT_HEADER }}
          JWT_PREFIX: ${{ secrets.JWT_PREFIX }}
        run: |
          mvn clean compile --batch-mode --no-transfer-progress \
            -Djwt.secret="${JWT_SECRET}" \
            -Djwt.token.expiration="${JWT_EXPIRATION}" \
            -Djwt.token.header="${JWT_HEADER}" \
            -Djwt.token.prefix="${JWT_PREFIX}"

      - name: Run tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_HEADER: ${{ secrets.JWT_HEADER }}
          JWT_PREFIX: ${{ secrets.JWT_PREFIX }}
        run: |
          mvn test --batch-mode --no-transfer-progress \
            -Djwt.secret="${JWT_SECRET}" \
            -Djwt.token.expiration="${JWT_EXPIRATION}" \
            -Djwt.token.header="${JWT_HEADER}" \
            -Djwt.token.prefix="${JWT_PREFIX}"
