name: CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'

jobs:
  checkout_code:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  archive_dependencies:
    needs: checkout_code
    runs-on: self-hosted
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Restore local Maven cache
        run: mkdir -p ~/.m2/repository; if [ -f maven_cache.tar.gz ]; then tar xzf maven_cache.tar.gz -C ~/.m2; fi

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Archive Maven dependencies
        run: tar czvf maven_dependencies.tgz -C ~/.m2/repository .

      - name: Upload Maven dependencies artifact
        uses: actions/upload-artifact@v2
        with:
          name: maven-dependencies
          path: ./maven_dependencies.tgz

  sca_testing:
    needs: archive_dependencies
    runs-on: self-hosted
    steps:
      - name: Download Maven dependencies archive
        uses: actions/download-artifact@v2
        with:
          name: maven-dependencies
          path: .

      - name: Extract Maven dependencies
        run: tar xvf maven_dependencies.tgz

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk test
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: false

  build:
    needs: sca_testing
    runs-on: self-hosted
    steps:
      - name: Download Maven dependencies archive
        uses: actions/download-artifact@v2
        with:
          name: maven-dependencies
          path: .

      - name: Extract Maven dependencies
        run: tar xvf maven_dependencies.tgz

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_HEADER: ${{ secrets.JWT_HEADER }}
          JWT_PREFIX: ${{ secrets.JWT_PREFIX }}
        run: |
          mvn clean compile --batch-mode --no-transfer-progress \
          -Djwt.secret="${JWT_SECRET}" \
          -Djwt.token.expiration="${JWT_EXPIRATION}" \
          -Djwt.token.header="${JWT_HEADER}" \
          -Djwt.token.prefix="${JWT_PREFIX}"

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_HEADER: ${{ secrets.JWT_HEADER }}
          JWT_PREFIX: ${{ secrets.JWT_PREFIX }}
        run: |
          mvn test --batch-mode --no-transfer-progress \
          -Djwt.secret="${JWT_SECRET}" \
          -Djwt.token.expiration="${JWT_EXPIRATION}" \
          -Djwt.token.header="${JWT_HEADER}" \
          -Djwt.token.prefix="${JWT_PREFIX}"
